apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 120
  template:
    spec:
      containers:
      - name: django-app
        image: django-app:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: django-app-config
        command: ["python3", "manage.py", "migrate"]
      restartPolicy: Never