apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  startingDeadlineSeconds: 20
  schedule: "* 0 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: django-app
              image: django-app:latest
              imagePullPolicy: IfNotPresent
              envFrom:
              - configMapRef:
                  name: django-app-config
              command: ["python3", "manage.py", "clearsessions"]