apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: edu-jovial-mclean
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - name: nginx-listener
      containerPort: 80